#!/usr/bin/env bash
# Project Brain — interactive bootstrap for a fresh production VM.
#
# What it does, in order:
#   1. Verifies docker + docker compose are available.
#   2. Prompts for the deployment essentials (domain, email, IdP, LLM key).
#   3. Generates fresh secrets (BRAIN_MASTER_KEY, AUTH_SECRET, INTERNAL_SERVICE_TOKEN, POSTGRES_PASSWORD).
#   4. Writes .env (refusing to clobber an existing one).
#   5. Pulls every image at the requested IMAGE_TAG.
#   6. Runs the one-shot migrate service.
#   7. Brings up the full prod stack (base + prod overlay).
#   8. Polls /api/health until readiness=true (5 minute budget).
#
# Re-run safely: aborts in step 4 if .env already exists. Use the regular
# `docker compose ... up -d` flow on subsequent boots.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
warn() { printf "\033[33m%s\033[0m\n" "$*"; }
fail() { printf "\033[31merror:\033[0m %s\n" "$*" >&2; exit 1; }

bold "Project Brain — production install"
echo

# --- Preflight ----------------------------------------------------------
command -v docker >/dev/null 2>&1 || fail "docker not found. Install Docker Engine 24+ and re-run."
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not available."
command -v openssl >/dev/null 2>&1 || fail "openssl not found (used to generate secrets)."

if [ -f .env ]; then
  fail ".env already exists. Either back it up and remove it, or run docker compose directly."
fi

if [ ! -f .env.example ]; then
  fail ".env.example missing — are you running this from the repo root?"
fi

# --- Prompts ------------------------------------------------------------
ask() {
  local prompt="$1" default="${2:-}" var
  if [ -n "$default" ]; then
    read -r -p "$prompt [$default]: " var
    echo "${var:-$default}"
  else
    while [ -z "${var:-}" ]; do read -r -p "$prompt: " var; done
    echo "$var"
  fi
}

ask_secret() {
  local prompt="$1" var
  while [ -z "${var:-}" ]; do
    read -r -s -p "$prompt: " var
    echo
  done
  echo "$var"
}

bold "1/3 Domain & TLS"
APP_DOMAIN=$(ask "Public domain (e.g. brain.acme.com)")
ACME_EMAIL=$(ask "Contact email for Let's Encrypt")
SUPER_ADMIN_EMAIL=$(ask "Initial super-admin email (auto-promoted on first sign-in)")
echo

bold "2/3 LLM provider"
echo "  1) Google Gemini"
echo "  2) Anthropic Claude"
echo "  3) OpenAI"
LLM_CHOICE=$(ask "Choose [1-3]" "1")
case "$LLM_CHOICE" in
  1) LLM_PROVIDER=google;    LLM_MODEL_DEFAULT=gemini-3-flash-preview;     KEY_PROMPT="GOOGLE_GENERATIVE_AI_API_KEY" ;;
  2) LLM_PROVIDER=anthropic; LLM_MODEL_DEFAULT=claude-sonnet-4-6;          KEY_PROMPT="ANTHROPIC_API_KEY" ;;
  3) LLM_PROVIDER=openai;    LLM_MODEL_DEFAULT=gpt-4o-mini;                KEY_PROMPT="OPENAI_API_KEY" ;;
  *) fail "invalid choice" ;;
esac
LLM_MODEL=$(ask "Model id" "$LLM_MODEL_DEFAULT")
LLM_API_KEY=$(ask_secret "$KEY_PROMPT")
echo

bold "3/3 Image source"
IMAGE_REGISTRY=$(ask "Image registry" "ghcr.io/neusis-ai-org")
IMAGE_TAG=$(ask "Image tag (e.g. v1.4.2 or latest)" "latest")
echo

# --- Secrets generation -------------------------------------------------
bold "Generating secrets"
BRAIN_MASTER_KEY=$(openssl rand -base64 32)
AUTH_SECRET=$(openssl rand -base64 32)
INTERNAL_SERVICE_TOKEN=$(openssl rand -hex 32)
GRAPHIFY_SIDECAR_TOKEN=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)

# --- Write .env ---------------------------------------------------------
bold "Writing .env"
APP_URL="https://$APP_DOMAIN"
umask 077
cat > .env <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit by hand or re-run install.sh after backing this file up.

# --- App ----------------------------------------------------------------
NODE_ENV=production
APP_URL=$APP_URL
APP_DOMAIN=$APP_DOMAIN
ACME_EMAIL=$ACME_EMAIL

BRAIN_MASTER_KEY=$BRAIN_MASTER_KEY
INTERNAL_SERVICE_TOKEN=$INTERNAL_SERVICE_TOKEN

# --- Key management -----------------------------------------------------
# local (default): credentials are encrypted at rest with BRAIN_MASTER_KEY
# above, and the GitHub App PEM is stored encrypted. For a "no plaintext keys"
# AWS deployment, set KMS_PROVIDER=aws and the refs below: credential
# encryption switches to KMS envelope encryption (DEK wrapped by KMS_KEY_REF)
# and the GitHub App private key is imported into a non-exportable KMS key at
# registration. With aws you can drop BRAIN_MASTER_KEY once existing rows are
# migrated (see scripts/reencrypt-kms.ts and docs/security.md).
KMS_PROVIDER=local
# KMS_KEY_REF=arn:aws:kms:us-east-1:ACCOUNT:key/UUID
# KMS_SIGNING_KEY_REF is populated automatically by the GitHub App import flow.

# Required by the worker and graphify-sidecar. Authenticates the worker's
# calls into the sidecar's HTTP API; the worker refuses to start without it.
GRAPHIFY_SIDECAR_TOKEN=$GRAPHIFY_SIDECAR_TOKEN
GRAPHIFY_EGRESS_ALLOWED_HOSTS=generativelanguage.googleapis.com,api.openai.com,api.anthropic.com

# --- Database & queue ---------------------------------------------------
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgres://brain:$POSTGRES_PASSWORD@postgres:5432/projectbrain
REDIS_URL=redis://redis:6379

# --- Auth.js ------------------------------------------------------------
AUTH_SECRET=$AUTH_SECRET
AUTH_URL=$APP_URL
AUTH_ALLOWED_EMAIL_DOMAINS=
INITIAL_SUPER_ADMIN_EMAIL=$SUPER_ADMIN_EMAIL

# Microsoft Entra ID (Azure AD). Configure in the Azure portal, then fill
# these in and restart: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d web
# Redirect URI to register: $APP_URL/api/auth/callback/microsoft-entra-id
AUTH_AZURE_AD_TENANT_ID=
AUTH_AZURE_AD_CLIENT_ID=
AUTH_AZURE_AD_CLIENT_SECRET=

DEV_AUTH_ENABLED=false

# GitHub App: registered through /admin/integrations after boot. No env vars.

# Atlassian OAuth: configured through /admin/integrations after boot.

# --- LLM ----------------------------------------------------------------
LLM_PROVIDER=$LLM_PROVIDER
LLM_MODEL=$LLM_MODEL
GOOGLE_GENERATIVE_AI_API_KEY=$([ "$LLM_PROVIDER" = google    ] && echo "$LLM_API_KEY")
ANTHROPIC_API_KEY=$(           [ "$LLM_PROVIDER" = anthropic ] && echo "$LLM_API_KEY")
OPENAI_API_KEY=$(              [ "$LLM_PROVIDER" = openai    ] && echo "$LLM_API_KEY")

# --- Scheduler ----------------------------------------------------------
SCHEDULER_ENABLED=true

# --- Observability ------------------------------------------------------
SENTRY_DSN=
LOG_LEVEL=info

# --- Backups (override defaults if needed) ------------------------------
BACKUP_KEEP_DAYS=7
BACKUP_KEEP_WEEKS=4
BACKUP_KEEP_MONTHS=6
WORKSPACE_BACKUP_RETENTION_DAYS=14

# --- Release / image tags -----------------------------------------------
IMAGE_REGISTRY=$IMAGE_REGISTRY
IMAGE_TAG=$IMAGE_TAG
APP_VERSION=$IMAGE_TAG
GIT_SHA=unknown
BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- Upgrade verification (set true once cosign is on the host) ---------
COSIGN_VERIFY=false
EOF
chmod 600 .env

mkdir -p backups/postgres backups/workspace
chmod 700 backups

# --- Compose up ---------------------------------------------------------
bold "Pulling images ($IMAGE_REGISTRY:$IMAGE_TAG)"
docker compose -f docker-compose.yml -f docker-compose.prod.yml pull

bold "Running migrations"
docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm migrate

bold "Starting the stack"
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

# --- Readiness ----------------------------------------------------------
bold "Waiting for readiness (5 minute budget)"
deadline=$(( $(date +%s) + 300 ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  body="$(docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T web wget -qO- http://127.0.0.1:3000/api/health 2>/dev/null || true)"
  if echo "$body" | grep -q '"readiness":true'; then
    echo
    bold "Project Brain is up."
    echo "  URL:           $APP_URL"
    echo "  Super admin:   $SUPER_ADMIN_EMAIL"
    echo "  Health:        $APP_URL/api/health"
    echo "  Backups dir:   $REPO_ROOT/backups"
    echo
    echo "Next steps:"
    echo "  - Point DNS at this server (A/AAAA → public IP)."
    echo "  - Wire up Microsoft Entra ID (AUTH_AZURE_AD_*) for SSO."
    echo "  - Read docs/BACKUP.md to verify the restore drill."
    exit 0
  fi
  sleep 5
done

warn "Readiness not reached within 5 minutes. Inspect:"
echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml logs --tail=200 web worker"
echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml ps"
exit 1
